name: Despliegue de Plataforma de Cursos en Windows

on:
  push:
    branches:
      - main

jobs:
  deploy-to-windows:
    # Se ejecuta en su runner
    runs-on: self-hosted

    steps:
      # Paso 1: Clona el código más reciente del repositorio
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      # El paso "Configurar Python" ha sido ELIMINADO.
      # El runner usará el Python ya instalado en el servidor.

      # Paso 2: Instala o actualiza las dependencias necesarias
      - name: 2. Instalar dependencias
        run: pip install -r requirements.txt
        shell: cmd

      # Paso 3: Reinicia la aplicación reiniciando la Tarea Programada
      - name: 3. Reiniciar la aplicación (Tarea Programada)
        run: |
          schtasks /end /tn "AppPlataformaCursos"
          schtasks /run /tn "AppPlataformaCursos"
        shell: cmd
