name: Despliegue de Plataforma de Cursos en Windows

# Se ejecuta con cada push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy-to-windows:
    # Se ejecuta en el runner que configuró en su servidor
    runs-on: self-hosted

    steps:
      # 1. Clona el código más reciente del repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python para el script
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Ajustar a su versión

      # 3. Instala o actualiza las dependencias necesarias
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # 4. Reinicia la aplicación reiniciando la Tarea Programada
      - name: Reiniciar la aplicación (Tarea Programada)
        run: |
          echo "Deteniendo la tarea si se esta ejecutando..."
          schtasks /end /tn "AppPlataformaCursos"
          echo "Iniciando la tarea con el nuevo codigo..."
          schtasks /run /tn "AppPlataformaCursos"
        shell: cmd
